# Generated by Django 3.2.6 on 2021-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
