# Generated by Django 3.2.6 on 2021-10-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211031_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_data',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
